In [1]:
import pandas as pd
import requests

In [2]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [7]:
df=pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [8]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,229.3482,8.974,1618
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,82.1095,8.722,30513
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,44.5504,8.687,23004
3,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,251.2943,8.666,4775
4,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,28.5329,8.572,13948
5,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,23.5327,8.569,17495
6,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,22.8868,8.562,10017
7,1330021,Remarkably Bright Creatures,Through unlikely bonds formed during night shi...,2026-05-07,48.7964,8.563,576
8,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,34.8132,8.535,18376
9,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,38.9118,8.531,35858
10,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,17.0706,8.500,4591
11,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,29.3770,8.507,19300
12,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-17,44.3458,8.499,26611
13,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,34.6159,8.494,20691
14,1181678,¿Quieres ser mi hijo?,"Lu, a conformist woman in her forties, learns ...",2023-09-21,12.2159,8.500,354
15,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,34.6646,8.483,30251
16,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-08-26,31.1397,8.481,12598
17,157336,Interstellar,The adventures of a group of explorers who mak...,2014-11-05,71.0258,8.477,39940
18,429,"The Good, the Bad and the Ugly",While the Civil War rages on between the Union...,1966-12-23,25.4239,8.468,9669
19,13,Forrest Gump,A man with a low IQ has accomplished great thi...,1994-06-23,27.9753,8.465,29802

In [9]:
df=pd.DataFrame()

In [11]:
for i in range(1,429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df=pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df=pd.concat([df, temp_df], ignore_index=True)

In [12]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,229.3482,8.974,1618
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,82.1095,8.722,30513
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,44.5504,8.687,23004
3,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,251.2943,8.666,4775
4,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,28.5329,8.572,13948
...,...,...,...,...,...,...,...
8555,675531,Dark Harvest,"In a small Midwestern town, a deadly annual ri...",2023-10-11,2.2095,6.000,307
8556,10066,House of Wax,A group of unwitting teens are stranded near a...,2005-05-05,5.4298,6.030,3348
8557,2370,Topaz,"Copenhagen, Denmark, 1962. When a high-ranking...",1969-12-17,2.6695,6.000,417
8558,328595,Parallels,An underground MMA fighter must confront his s...,2015-03-01,1.1854,6.000,390
8559,209355,The French Minister,Alexandre Taillard de Vorms is a force to be r...,2013-11-06,0.6924,6.028,302

In [13]:
df.to_csv('movies.csv')